# 数据源配置
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/dingtou?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=true
    username: dingtou
    password: DingTou.Me



  # FREEMARKER (FreeMarkerAutoConfiguration)
  freemarker:
    allow-request-override: false
    cache: true
    check-template-location: true
    charset: UTF-8
    content-type: text/html
    expose-request-attributes: false
    expose-session-attributes: false
    expose-spring-macro-helpers: false
    suffix: .ftl
    template-loader-path: classpath:/templates/ #comma-separated list

  resources:
    static-locations: classpath:/static/


  jackson:
    generator:
      write_numbers_as_strings: true
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null

me:
  dingtou:
    #登陆配置
    login:
      needLogin: false
      defaultOwner: default
      #loginUrl: https://github.com/login/oauth/authorize?client_id=700a1ae2a42328279390
      loginUrl: https://api.weibo.com/oauth2/authorize?client_id=xxxxxxxxxxx&response_type=code&redirect_uri=https://dingtoume.cn/login/oauth_weibo
      secretKey: d7edf5704cae2e5105b2c99d6a4e32b655c36f8a3ae2dcc22ea4e7df1be8803e
    #集成登陆配置
    oauth:
      github:
        client_id: 700a1ae2a42328279390
        client_secret: bdca3d91e0867d5a1c4bbf01dc61a1f22a18eeff
        redirect_uri: https://dingtoume.cn/login/oauth_github
      weibo:
        client_id: xxxxxxxxxxx
        client_secret: xxxxxxxxxxxxxxxxxxxx
        redirect_uri: https://dingtoume.cn/login/oauth_weibo
